### ISSUE TITLE
Incompatible network protocal version

### ISSUE THREAD

**Issue by FoodyYoutoob** [HighestDreams/CustomNPC#10]
Every-time I start my server it says on Custom NPC “Incompatible network protocal version (plugin requires one of: 361, 388, 389, 390, 407, 408, 440, 448)”

**Comment by HighestDreams** [comment]
Which version of pocket-mine you use give me your protocol? 
For this, use these steps :

1. Run you pocket-mine server
2. Type command /ver
3. Now you can see your version & protocol, sent the info here to i fix the plugin.

**Comment by FoodyYoutoob** [comment]
Protocal 465

**Comment by HighestDreams** [comment]
Edited, download the plugin from github (Not poggit) run your server, tell me if it works fine.
