### ISSUE TITLE
Typo leading to a crash

### ISSUE THREAD

**Issue by Ifera** [HighestDreams/CustomNPC#5]
There is a typo in `NPC_EDITGMODE_TUTORIAL2` which leads to a crash. It should be `NPC_EDITMODE_TUTORIAL2` if I am not mistaken.

https://github.com/HighestDreams/CustomNPC/blob/9c3bd100e72b9eff35ea16336e2563929a7166d0/src/HighestDreams/CustomNPC/NPC.php#L113

**Comment by HighestDreams** [comment]
Done.
