### ISSUE TITLE
Typo again, leading to a crash

### ISSUE THREAD

**Issue by Ifera** [HighestDreams/CustomNPC#6]
This here:

https://github.com/HighestDreams/CustomNPC/blob/9c3bd100e72b9eff35ea16336e2563929a7166d0/src/HighestDreams/CustomNPC/NPC.php#L92

Should have been:

```php
$player->sendMessage(self::PREFIX . self::$lang::get(self::$lang::RCA_NOTFOUND));
```

**Comment by HighestDreams** [comment]
Done.
