### ISSUE TITLE
Consider using Entity::createBaseNBT()

### ISSUE THREAD

**Issue by Ifera** [HighestDreams/CustomNPC#7]
Consider using `Entity::createBaseNBT()` instead of [this](https://github.com/HighestDreams/CustomNPC/blob/main/src/HighestDreams/CustomNPC/NPC.php#L128-L143) bulky mess.

```php
$nbt = Entity::createBaseNBT($player, $player->getMotion(), $player->getYaw(), $player->getPitch());
```

**Comment by HighestDreams** [comment]
Done, i was testing smth i forget to re-change code to normal
