### ISSUE TITLE
Invalid else block

### ISSUE THREAD

**Issue by Ifera** [HighestDreams/CustomNPC#8]
What's the point of [this](https://github.com/HighestDreams/CustomNPC/blob/9c3bd100e72b9eff35ea16336e2563929a7166d0/src/HighestDreams/CustomNPC/EventsHandler.php#L127-L135) else block? 
During my testing I found that this causes the Y value of the other player/entity to decrease by 1.

**Comment by HighestDreams** [comment]
It was for testing other entities but i forgotten to remove that 'else' block.
